#!/bin/sh
#
# Build a prometheus+grafana docker image to collect linkerd metrics.
#
# usage:
# dockerize [docker-tag]

set -e

VIZ_TAG="buoyantio/linkerd-viz:latest"
if [ "$1" != "" ]; then
  VIZ_TAG="$1"
fi

BUILD=/tmp/linkerd-viz
PROM_TAG=prom/prometheus:v1.1.3
GRAF_TAG=grafana/grafana:3.1.1

rm -rf $BUILD
mkdir -p $BUILD/bin
mkdir -p $BUILD/etc/prometheus
mkdir -p $BUILD/etc/grafana/dashboards

cp Dockerfile                  $BUILD/Dockerfile
cp linkerd-viz                 $BUILD/linkerd-viz
cp prometheus-*.yml            $BUILD/etc/prometheus/
cp grafana.ini                 $BUILD/etc/grafana/grafana.ini
cp prometheus_data_source.json $BUILD/etc/grafana/prometheus_data_source.json
cp linkerd-viz-dashboard.json  $BUILD/etc/grafana/dashboards/linkerd-viz-dashboard.json

PROM_BUILD=$(docker create $PROM_TAG)

docker cp $PROM_BUILD:/bin/prometheus                    $BUILD/bin/prometheus
docker cp $PROM_BUILD:/bin/promtool                      $BUILD/bin/promtool
docker cp $PROM_BUILD:/etc/prometheus/console_libraries/ $BUILD/etc/prometheus/console_libraries
docker cp $PROM_BUILD:/etc/prometheus/consoles/          $BUILD/etc/prometheus/consoles

docker rm -vf $PROM_BUILD >/dev/null 2>&1 || true

docker build --tag=$VIZ_TAG $BUILD
docker push $VIZ_TAG
