global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
- job_name: 'linkerd'
  metrics_path: /admin/metrics/prometheus

  kubernetes_sd_configs:
  - api_server: 'http://localhost:8001'
    role: endpoints

  relabel_configs:
  # only collect from linkerd's
  - source_labels: ['__meta_kubernetes_service_name']
    regex:         (.*l5d$)
    action:        keep
  - source_labels: [__address__]
    action: replace
    target_label: __address__
    regex: (.+)(?::\d+)
    replacement: $1:9990
  # strip off port
  - source_labels: [__address__]
    action: replace
    target_label: instance
    regex: (.+)(?::\d+)
    replacement: $1

  metric_relabel_configs:
  # remove explicit linkerd proxy ports
  - source_labels: [__name__]
    action:        replace
    target_label:  __name__
    regex:         rt:([^:]+):srv:0_0_0_0:[^:]+:(.*)
    replacement:   rt:$1:srv:0_0_0_0:port:$2
  # write service names into label {service:"app1"}
  - source_labels: [__name__]
    action:        replace
    target_label:  service
    regex:         rt:[^:]+:dst:id.*:_:io_l5d_k8s:[^:]+:[^:]+:([^:]+):.*
    replacement:   $1
  # remove service name from metric (linkerd:outgoing:requests)
  - source_labels: [__name__]
    action:        replace
    target_label:  __name__
    regex:         rt:([^:]+):dst:id.*:_:io_l5d_k8s:[^:]+:[^:]+:[^:]+:(.*)
    replacement:   linkerd:$1:$2
