global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
- job_name: 'linkerd'
  metrics_path: /admin/metrics/prometheus

  marathon_sd_configs:
  - servers:
    - 'http://marathon.mesos:8080'

  relabel_configs:
  # only collect from linkerd's
  - source_labels: ['__meta_marathon_app']
    regex:         (.*linkerd$)
    action:        keep
  # strip off port
  - source_labels: [__address__]
    action: replace
    target_label: instance
    regex: (.+)(?::\d+)
    replacement: $1

  metric_relabel_configs:
  # remove explicit linkerd proxy ports
  - source_labels: [__name__]
    action:        replace
    target_label:  __name__
    regex:         rt:([^:]+):srv:0_0_0_0:[^:]+:(.*)
    replacement:   rt:$1:srv:0_0_0_0:port:$2
  # write service names into label {service:"app1"}
  - source_labels: [__name__]
    action:        replace
    target_label:  service
    regex:         rt:[^:]+:dst:id.*:_:io_l5d_marathon:([^:]+):.*
    replacement:   $1
  # remove service name from metric (linkerd:outgoing:requests)
  - source_labels: [__name__]
    action:        replace
    target_label:  __name__
    regex:         rt:([^:]+):dst:id.*:_:io_l5d_marathon:[^:]+:(.*)
    replacement:   linkerd:$1:$2
