global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
- job_name: 'linkerd'
  metrics_path: /admin/metrics/prometheus

  marathon_sd_configs:
  - servers:
    - 'http://marathon.mesos:8080'

  relabel_configs:
  # only collect from linkerd's
  - source_labels: ['__meta_marathon_app']
    regex:         (.*linkerd$)
    action:        keep
  # strip off port
  - source_labels: [__address__]
    action: replace
    target_label: instance
    regex: (.+)(?::\d+)
    replacement: $1

  metric_relabel_configs:
  # simplify client names
  # %/io.l5d.port/4141/#/io.l5d.marathon/webapp => webapp
  - source_labels: [client]
    action:        replace
    target_label:  client
    regex:         .*io\.l5d\.marathon\/(.*)
    replacement:   $1
  # simplify service names
  # /svc/webapp => webapp
  - source_labels: [service]
    action:        replace
    target_label:  service
    regex:         .*svc\/(.*)
    replacement:   $1
